// ============================================================================================
// LOCALHOST Deploy
// ============================================================================================
### Get all students
GET http://localhost:3000/students

### Get students by id
GET http://localhost:3000/students/65059d846330c2ffbe4725a9

### Create students
POST http://localhost:3000/students HTTP/1.1
content-type: application/json

{
     "name": "Williams",
    "school": "BYU",
    "class": "2A",
    "subject": "maths",
    "year": "1910"
}

### PUT students
PUT http://localhost:3000/students/63c2683c355744f60488f860 HTTP/1.1
content-type: application/json

{
   "name": "Gladys",
    "school": "KNUST",
    "class": "3A1",
    "subject": "Science",
    "year": "2000"
}

### re-PUT students (put back the original entry)
PUT http://localhost:3000/students/63c2683c355744f60488f860 HTTP/1.1
content-type: application/json

{
    "name": "Ama",
    "school": "UCC",
    "class": "AB1",
    "subject": "ICT",
    "year": "2020"
}

### DELETE students
DELETE http://localhost:3000/students/650c1dd03874e554214feddb HTTP/1.1


